### ISSUE TITLE
Rusqlite should be supported.

### ISSUE THREAD

**Issue by knarkzel** [tvallotton/rocket_auth#24]
Heya, I'm using this crate for my project: https://github.com/knarkzel/elixir, where I'm using `rusqlite` instead of `sqlx`. Could you add `rusqlite` to this crate? I have forked it and added needed changes here: https://github.com/knarkzel/rocket_auth/blob/master/src/db/sqlite/mod.rs.

Thanks!

**Comment by tvallotton** [comment]
`Rusqlite` is now supported.

**Comment by tvallotton** [comment]
Hey, you should also consider adding a `rev` in your `Cargo.toml` file so you're code doesn't break with every commit. Something like this should work until `rocket` 0.5 comes out.   
```ini
[dependencies.rocket_auth]
git = "https://github.com/tvallotton/rocket_auth"
rev = "733e8f4b096f25886c5606de6a2c8b14f5e18884"
features = ["rusqlite"]
```
