### ISSUE TITLE
Check if String is same as hashed password

### ISSUE THREAD

**Issue by DerPizzaBoi** [tvallotton/rocket_auth#38]
I am currently implementing a feature to change a users password and email. To do that the user has to reenter the password, even if he is logged in. After that i want to hash the password and compare it to the current one.
My Problem is:
I can't find a method to easily hash a String with the same salt as the current password. For now i can try to use the argon2 crate as you do and hash it that way, but It would be nice to have a function to compare the hashed password to a string. Maybe you can add that in the next release :)

**Comment by tvallotton** [comment]
Hi, feel free to make a PR for it. Unfortunately I have been a little busy lately, so it make take me some time before I can take a look at this.

**Comment by DerPizzaBoi** [comment]
No problem. If i have time i will try to implement it and make a PR

**Comment by DerPizzaBoi** [comment]
This was implemented in [fe538aa](https://github.com/tvallotton/rocket_auth/commit/fe538aafbbc3f6868bf9bca60a7aec613558c09c)
