### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DerPizzaBoi** [tvallotton/rocket_auth#41]
So the next crate does not compile anymore, because i can't find the id, as id is not a filed anymore. It can be fixed by changing line 316 in auth.rs from `let user: User = self.users.get_by_id(session.id).await?;` to `let user: User = self.users.get_by_id(session.id()?).await?;`. I tried to fix it myself, it works locally, but i can't update my fork

**Comment by tvallotton** [comment]
Hi, yes, I noticed that while I was merging next with some of my local unpushed changes. I will push the fixed version soon.
