### ISSUE TITLE
Update sqlx to v0.6

### ISSUE THREAD

**Issue by yzernik** [tvallotton/rocket_auth#46]
Support the newest release of sqlx: https://github.com/launchbadge/sqlx/releases/tag/v0.6.0

**Comment by tvallotton** [comment]
Yes, this sounds like something to include in the next release.

**Comment by yzernik** [comment]
Looks like this is done? https://github.com/tvallotton/rocket_auth/commit/1321b41ac5c1cbb8ee80f01022a2bc6b921c1144

**Comment by tvallotton** [comment]
Oh, yeah, its done
